spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 4287...
            client-secret: GOCSPX-...
            scope:
              - email
              - profile
        provider:
          google:
            issuer-uri: https://accounts.google.com

  app:
    auth:
      jwt-secret: "DevisionSuperSecretKeyForJWT123456"
      jwt-expiration-ms: 180000
      frontend-redirect-url: "http://localhost:5173/auth/callback"

  application:
    name: authentication-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb+srv://ungxuandat11092001_db_user:rimUzRGKNrMsbCmb@authentication.wltiegf.mongodb.net/authentication-db?retryWrites=true&w=majority&appName=Authentication
