server:
  port: ${SERVER_PORT:8087}
  forward-headers-strategy: framework

spring:
  application:
    name: authentication-service

  cloud:
    config:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ${GOOGLE_SCOPES:email,profile}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          google:
            issuer-uri: ${GOOGLE_ISSUER_URI:https://accounts.google.com}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


  mongodb:
    uri: ${MONGODB_URI}

app:
  redis:
    revocation:
      host: ${REDIS_REVOCATION_HOST:127.0.0.1}
      port: ${REDIS_REVOCATION_PORT:6380}
      password: ${REDIS_REVOCATION_PASSWORD}
  super-admin:
    email: ${APP_SUPER_ADMIN_EMAIL:s3932156@rmit.edu.vn}
    password: ${APP_SUPER_ADMIN_PASSWORD:123123}
  auth:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: ${JWT_EXPIRATION_MS:180000}
    jwt-refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
    cookie-secure: true
    access-token-expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS:180000}     # default 3 minutes
    refresh-token-expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS:2592000000} # default 30 days
    frontend-redirect-url: ${FRONTEND_REDIRECT_URL}
    frontend-banned-url: ${FRONTEND_BANNED_URL}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:${EUREKA_INSTANCE_HOSTNAME}}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

