spring:
  application:
    name: authorization-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: ${MONGODB_URI_AUTHORIZATION}

app:
  auth:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: ${JWT_EXPIRATION_MS}

server:
  port: 8082

springdoc:
  pathsToMatch: /api/**

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:${EUREKA_INSTANCE_HOSTNAME}}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
