server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: subscription-service

  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

kafka:
  topics:
    payment-initiated: ${KAFKA_PAYMENT_INITIATED_TOPIC:payment-initiated}
    payment-success: ${KAFKA_PAYMENT_SUCCESS_TOPIC:payment-success}
    payment-failed: ${KAFKA_PAYMENT_FAILED_TOPIC:payment-failed}
    job-post-updates: ${KAFKA_JOB_POST_UPDATES_TOPIC:job-post-updates}
    applicant-profile-updates: ${KAFKA_APPLICANT_PROFILE_UPDATES_TOPIC:subscription-salary-update}

payment:
  consumer:
    enabled: ${PAYMENT_CONSUMER_ENABLED:false}

  forward:
    enabled: ${PAYMENT_FORWARD_ENABLED:false}
    base-url: ${PAYMENT_BASE_URL:http://localhost:8084}
    initiate-path: /payments/initiate
    bearer: ${PAYMENT_FORWARD_AUTH_TOKEN:}

notification:
  consumer:
    enabled: ${NOTIFICATION_CONSUMER_ENABLED:false}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:${EUREKA_INSTANCE_HOSTNAME}}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
