server:
  port: ${SERVER_PORT:10789}
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - Origin
            exposedHeaders:
              - Set-Cookie
            allowCredentials: true

      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**,/oauth2/**,/login/oauth2/**

        - id: authorization-service
          uri: lb://AUTHORIZATION-SERVICE
          predicates:
            - Path=/api/v1/authorization/**

        - id: application-service-files
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/api/files/**

        - id: application-service-applications
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/api/v1/applications/**

        - id: applicant-service
          uri: lb://APPLICANT-SERVICE
          predicates:
            - Path=/api/v1/applicants/**

        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/subscriptions/**
      forwarded:
        enabled: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:${EUREKA_INSTANCE_HOSTNAME}}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
