server:
  port: ${SERVER_PORT}

spring:
  application:
    name: applicant-service

  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


#Default MongoDB(VN)
  mongodb:
    database: ${MONGODB_DATABASE}
    uri: ${MONGODB_URI}
app:
  auth:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: ${JWT_EXPIRATION_MS}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:${EUREKA_INSTANCE_HOSTNAME}}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
